version: '3'

services:
  erlang:
    image: erlang:22.3
    volumes:
      - ../:/emqx_auth_redis
    networks:
      - emqx_bridge
    depends_on:
      - redis_server
    tty: true

  redis_server:
    image: redis:6.0.9
    volumes:
      - ../test/emqx_auth_redis_SUITE_data/certs:/tls
    command:
      - redis-server
      - "--bind 0.0.0.0 ::"
      - --tls-port 6380
      - --tls-cert-file /tls/redis.crt
      - --tls-key-file /tls/redis.key
      - --tls-ca-cert-file /tls/ca.crt
    restart: always
    networks:
      - emqx_bridge

networks:
  emqx_bridge:
    driver: bridge
