version: '3.9'

services:
  erlang24:
    container_name: erlang24
    image: ghcr.io/emqx/emqx-builder/5.0-17:1.13.4-24.2.1-1-ubuntu20.04
    env_file:
      - conf.env
    environment:
      GITHUB_ACTIONS: ${GITHUB_ACTIONS}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_RUN_ID: ${GITHUB_RUN_ID}
      GITHUB_SHA: ${GITHUB_SHA}
      GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}
      GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}
      GITHUB_REF: ${GITHUB_REF}
    networks:
      - emqx_bridge
    volumes:
      - ../..:/emqx
      - emqx-shared-secret:/var/lib/secret
      - ./kerberos/krb5.conf:/etc/kdc/krb5.conf
      - ./kerberos/krb5.conf:/etc/krb5.conf
    working_dir: /emqx
    tty: true
    user: "${UID_GID}"

networks:
  emqx_bridge:
    driver: bridge
    name: emqx_bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.100.239.0/24
          gateway: 172.100.239.1
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1

volumes:   # add this section
  emqx-shared-secret:    # does not need anything underneath this
