version: '3.9'

services:
  erlang:
    container_name: erlang
#    image: emqx/build-env:erl23.2.7-ubuntu20.04
    image: twenty8/emqx:latest
    env_file:
      - conf.env
    environment:
      GITHUB_ACTIONS: ${GITHUB_ACTIONS}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_RUN_ID: ${GITHUB_RUN_ID}
      GITHUB_SHA: ${GITHUB_SHA}
      GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}
      GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}
      GITHUB_REF: ${GITHUB_REF}
      TEST_HOST_PLATFORM: "github_action_docker"
#    networks:
#      - emqx_bridge
    volumes:
      - ../..:/emqx
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /emqx
    tty: true

networks:
  emqx_bridge:
    driver: bridge
    name: emqx_bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.100.239.0/24
          gateway: 172.100.239.1
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
