version: '3.9'

services:
  mongo_server:
    container_name: mongo
    image: mongo:${MONGO_TAG}
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mqtt
    expose:
      - 27017
    networks:
      - emqx_bridge
    command:
      --ipv6
      --bind_ip_all
