version: '3.9'

services:
  redis_server_tls:
    container_name: redis-tls
    image: redis:${REDIS_TAG}
    volumes:
      - ./certs/server.crt:/etc/certs/redis.crt
      - ./certs/server.key:/etc/certs/redis.key
      - ./certs/ca.crt:/etc/certs/ca.crt
      - ./redis/single-tls:/usr/local/etc/redis
    ports:
      - "6380:6380"
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      emqx_bridge:
