name: $PROFILE
base: $SNAP_BASE
version: $EMQX_VERSION
summary: The most scalable open-source MQTT broker
description: |
  EMQX is the world's most scalable open-source MQTT broker with a high performance that connects 100M+ IoT devices in 1 cluster, while maintaining 1M message per second throughput and sub-millisecond latency.

  EMQX supports multiple open standard protocols like MQTT, HTTP, QUIC, and WebSocket. It's 100% compliant with MQTT 5.0 and 3.x standard, and secures bi-directional communication with MQTT over TLS/SSL and various authentication mechanisms.

  With the built-in powerful SQL-based rules engine, EMQX can extract, filter, enrich and transform IoT data in real-time. In addition, it ensures high availability and horizontal scalability with a masterless distributed architecture, and provides ops-friendly user experience and great observability.

  EMQX boasts more than 20K+ enterprise users across 50+ countries and regions, connecting 100M+ IoT devices worldwide, and is trusted by over 400 customers in mission-critical scenarios of IoT, IIoT, connected vehicles, and more, including over 70 Fortune 500 companies like HPE, VMware, Verifone, SAIC Volkswagen, and Ericsson.

  For more information, please visit the EMQX homepage (https://www.emqx.com/en).

grade: stable
confinement: strict

apps:
  emqx:
    command: bin/emqx foreground
    daemon: simple
    plugs:
      - network
      - network-bind
    environment:
      EMQX_NODE__DATA_DIR: $SNAP_DATA/data
      EMQX_NODE__COOKIE: secret
  ctl:
    command: bin/emqx ctl
    environment:
      EMQX_NODE__DATA_DIR: $SNAP_DATA/data
      EMQX_NODE__COOKIE: secret
    plugs:
      - network

parts:
  emqx:
    plugin: dump
    source: $PACKAGE_SOURCE
    stage-packages:
      - libsasl2-2
      - libodbc2
