{{- if .Values.ingress.wss.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "emqx.fullname" .) "wss" }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if or .Values.ingress.annotations .Values.ingress.wss.annotations }}
  annotations:
  {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.wss.annotations }}
    {{- toYaml .Values.ingress.wss.annotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
{{- if and .Values.ingress.wss.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.wss.ingressClassName }}
{{- end }}
  rules:
  {{- range $host := .Values.ingress.wss.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: {{ $.Values.ingress.wss.path | default "/mqtt" }}
        {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: {{ $.Values.ingress.wss.pathType | default "ImplementationSpecific" }}
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ include "emqx.fullname" $ }}
            port:
              number: {{ $.Values.service.ws }}
          {{- else }}
          serviceName: {{ include "emqx.fullname" $ }}
          servicePort: {{ $.Values.service.ws }}
          {{- end }}
  {{- end -}}
  {{- if .Values.ingress.wss.tls }}
  tls:
    {{- toYaml .Values.ingress.wss.tls | nindent 4 }}
  {{- end }}
{{- end }}
