---

name: Check Elixir Release Applications

on:
  pull_request:

jobs:
  elixir_apps_check:
    runs-on: ubuntu-22.04
    # just use the latest builder
    container: "ghcr.io/emqx/emqx-builder/5.0-34:1.13.4-25.1.2-3-ubuntu22.04"

    strategy:
      fail-fast: false
      matrix:
        profile:
          - emqx
          - emqx-enterprise
          - emqx-pkg
          - emqx-enterprise-pkg

    steps:
      - name: fix_git_permission
        run: git config --global --add safe.directory '/__w/emqx/emqx'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ensure rebar
        run: ./scripts/ensure-rebar3.sh
      - name: Work around https://github.com/actions/checkout/issues/766
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: check applications
        run: ./scripts/check-elixir-applications.exs
        env:
          MIX_ENV: ${{ matrix.profile }}
          PROFILE: ${{ matrix.profile }}
#      - name: check applications started with emqx_machine
#        run: ./scripts/check-elixir-emqx-machine-boot-discrepancies.exs
#        env:
#          MIX_ENV: ${{ matrix.profile }}

...
