# FIXME: temporary workflow for testing; remove later
name: Elixir Build (temporary)

concurrency:
  group: mix-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/emqx/emqx-builder/5.0-10:1.13.3-24.2.1-1-ubuntu20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: install tools
        run: apt update && apt install netcat-openbsd
      - name: elixir release
        run: make emqx-elixir
      - name: start release
        run: |
          cd _build/emqx/rel/emqx
          bin/emqx start
      - name: check if started
        run: |
          sleep 10
          nc -zv localhost 1883
          cd _build/emqx/rel/emqx
          bin/emqx ping
          bin/emqx ctl status
