---

name: Elixir Dependency Version Check

on: [pull_request, push]

jobs:
  elixir_deps_check:
    runs-on: ubuntu-20.04
    container: ghcr.io/emqx/emqx-builder/5.0-24:1.13.4-24.3.4.2-1-ubuntu20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ensure rebar
        run: ./scripts/ensure-rebar3.sh
      - name: Work around https://github.com/actions/checkout/issues/766
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: setup mix
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      - name: check elixir deps
        run: ./scripts/check-elixir-deps-discrepancies.exs

...
