name: Rerun apps version check
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Upload release assets"
    types:
      - completed

permissions:
  contents: read

jobs:
  rerun-apps-version-check:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: read
      checks: write
      actions: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: trigger re-run of app versions check on open PRs
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 scripts/rerun-apps-version-check.py
