---

name: Manage stale issues

on:
  schedule:
    # run hourly
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stale:
    if: github.repository == 'emqx/emqx'
    runs-on: ubuntu-22.04
    permissions:
      issues: write
      pull-requests: none

    steps:
      - name: Close Stale Issues
        uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          days-before-stale: 7
          days-before-close: 7
          exempt-issue-labels: 'internal,BUG,help wanted,#triage/accepted,#needs-triage,Feature,Enhancement'
          stale-issue-label: "#triage/stale"
          stale-issue-message: >-
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          # we don't want stalebot to analyze pull requests
          only-pr-labels: "ZZZDisabledZZZ"
          operations-per-run: 80

...
